// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3C1lbogFQZtJ5wIJKWmw3azjUb_nlATY',
    appId: '1:710207526324:web:5fe48a7b61ce078b404ee1',
    messagingSenderId: '710207526324',
    projectId: 'baridpoject',
    authDomain: 'baridpoject.firebaseapp.com',
    storageBucket: 'baridpoject.firebasestorage.app',
    measurementId: 'G-4S5K6ZMK9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-eizUxBd1TY-OEuKTEtzS-6iW2S-uD7s',
    appId: '1:710207526324:android:9504ee1ebe36b58b404ee1',
    messagingSenderId: '710207526324',
    projectId: 'baridpoject',
    storageBucket: 'baridpoject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeYgxcA0SrawsE1fQkhE7Eaxo0JjXZW18',
    appId: '1:710207526324:ios:cecdd2960fc92068404ee1',
    messagingSenderId: '710207526324',
    projectId: 'baridpoject',
    storageBucket: 'baridpoject.firebasestorage.app',
    iosBundleId: 'com.example.bareed',
  );
}
